global:
  accountId: "082111255551"
  region: "eu-central-1"
  envName: "frp2"
  domainExtKaltura: "frp2.ovp.kaltura.com"

App:
  env: frp2

  # repo details
  image:
    repository: "{{ .Values.global.accountId }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/push"
  initImage:
    repository: "{{ .Values.global.accountId }}.dkr.ecr.{{ .Values.global.region }}.amazonaws.com/push-init-py"

  # annotations
  annotations:
    vector.dev/s3: 'true'

# push configs
push:
  RABBIT_MQ_SERVER: http://pc-rabbitmq-1.frp2.ovp.kaltura.prod:5672,http://pc-rabbitmq-2.frp2.ovp.kaltura.prod:5672,http://pc-rabbitmq-3.frp2.ovp.kaltura.prod:5672
  rabbitUrl: pc-rabbitmq-1.frp2.ovp.kaltura.prod