kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.App.namespace }}
  name: {{ .Values.App.name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.App.name }}
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8086