apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.App.name }}
  namespace: {{ .Values.App.namespace }}
  labels:
    app: {{ .Values.App.name }}
spec:
  type: {{ .Values.services.type }}
  selector:
    app: {{ .Values.App.name }}
  ports:
  - protocol: TCP
    name: node
    port: {{ .Values.services.port }}
    targetPort: {{ .Values.services.targetPort }}
  - protocol: TCP
    name: monitor
    port: {{ .Values.push.MONITOR_PORT }}
    targetPort: {{ .Values.push.MONITOR_PORT }}
