App:
  # app details
  name: xxx
  env: xxx

  # ns to deploy
  namespace: push

  # how many pods
  replicas: 2

  # repository info
  image:
    repository: xxx/push
    tag: v1.2.1-661
  initImage:
    repository: xxx/push-init-py
    tag: latest
  pullPolicy: Always

  # container port
  containerPort: 80

  # pod affinity
  affinityKey: nodeAffinity
  affinityValue: frontend
  podAntiAffinity: true

  # toleration
  toleration:
    key: frontend
    value: frontend

  ## Rolling Updates ##
  maxSurge: 25%
  maxUnavailable: 25%

  # limits
  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 1
      memory: 4Gi

# service publish
services:
  type: ClusterIP
  port: 80
  targetPort: 80

# push configs
push:
  LOG_DIR: /var/log/pub-sub-server
  QUEUE_NAME: push_server
  RABBIT_MQ_SERVER: xxx
  RABBIT_MQ_SERVER_HOSTS: xxx
  SOCKET_IO_PORT: 80
  MONITOR_PORT: 8086
  confPath: /pub-sub-server/config
  confFile: config.ini
  rabbitUrl: xxx
  initConf: "/opt/config/config.ini.init"